apiVersion: 1

datasources:
  - name: k6 InfluxDB
    uid: au-kpis-k6-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    editable: false
    jsonData:
      httpMode: GET
