/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Australian KPIs API
 * Unified API for Australian public economic data.
 * OpenAPI spec version: 0.1.0
 */
/**
 * Lowercase hex-encoded SHA-256 digest (64 chars).
 * @minLength 64
 * @maxLength 64
 */
export type ArtifactId = string;

/**
 * Scorecard axis used by APS v1.
 */
export type Axis = typeof Axis[keyof typeof Axis];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Axis = {
  throughput: 'throughput',
  orientation: 'orientation',
} as const;

export type CodeDescription = string | null;

export type CodeParentId = null | CodeId;

/**
 * A single code within a codelist (e.g. `VIC` → "Victoria").
 */
export interface Code {
  /** The codelist this code belongs to. Denormalised here so a `Code`
emitted from the API is self-contained. */
  codelist_id: CodelistId;
  description?: CodeDescription;
  id: CodeId;
  name: string;
  parent_id?: CodeParentId;
}

/**
 * Identifier for a code within a codelist (e.g. `VIC`).
 */
export type CodeId = string;

export type CodelistDescription = string | null;

/**
 * A reusable vocabulary of codes attached to dimensions.
 */
export interface Codelist {
  codes: Code[];
  description?: CodelistDescription;
  id: CodelistId;
  name: string;
}

/**
 * Identifier for a codelist (e.g. `CL_STATE_AU`).
 */
export type CodelistId = string;

/**
 * Component-level score inside a sub-index.
 */
export interface ComponentScore {
  /** Component name. */
  component: string;
  /** Weight-aware coverage percentage. */
  coverage_pct: number;
  /** Component score in the axis scale. */
  score: number;
  /** Weight represented by this component. */
  weight: number;
}

/**
 * Confidence label exposed for configs, contributions, and snapshots.
 */
export type Confidence = typeof Confidence[keyof typeof Confidence];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Confidence = {
  high: 'high',
  medium: 'medium',
  low: 'low',
} as const;

/**
 * Lower and upper score bounds.
 */
export interface ConfidenceBand {
  /** Best-case score. */
  high: number;
  /** Worst-case score. */
  low: number;
}

/**
 * Contribution coverage state.
 */
export type CoverageStatus = typeof CoverageStatus[keyof typeof CoverageStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CoverageStatus = {
  resolved: 'resolved',
  stale: 'stale',
  missing_expected: 'missing_expected',
  coverage_gap: 'coverage_gap',
  manual_pending: 'manual_pending',
  visible_unscored: 'visible_unscored',
} as const;

/**
 * Request body for `POST /v1/subscriptions`.
 */
export interface CreateSubscriptionRequest {
  /** Optional dataflow filter. Empty means every dataflow update. */
  dataflow_ids?: DataflowId[];
  /** Absolute HTTP(S) URL to receive webhook deliveries. */
  url: string;
}

/**
 * Response body for `POST /v1/subscriptions`.
 */
export interface CreateSubscriptionResponse {
  /** Created subscription. */
  subscription: SubscriptionDetails;
}

export type DataflowDescription = string | null;

/**
 * A dataflow — a named collection of series sharing dimensions and measures.
 */
export interface Dataflow {
  /** Required attribution string shown to end-users alongside derived charts. */
  attribution: string;
  description?: DataflowDescription;
  /** Ordered list of dimension ids that key series within this dataflow. */
  dimensions: DimensionId[];
  frequency: Frequency;
  id: DataflowId;
  license: License;
  /** Measures published by this dataflow (index, rate, count, ...). */
  measures: MeasureId[];
  name: string;
  source_id: SourceId;
  /** Canonical citation URL. */
  source_url: string;
}

/**
 * Response envelope for `GET /v1/dataflows/{id}/codelists/{dim}`.
 */
export interface DataflowCodelistResponse {
  /** Codelist attached to the requested dimension. */
  codelist: Codelist;
  /** Requested dataflow id. */
  dataflow_id: DataflowId;
  /** Requested dimension id. */
  dimension_id: DimensionId;
}

/**
 * Response envelope for `GET /v1/dataflows/{id}`.
 */
export interface DataflowDetailResponse {
  /** Dataflow metadata. */
  dataflow: Dataflow;
  /** Ordered dimension metadata for the dataflow. */
  dimensions: Dimension[];
}

/**
 * Identifier for a dataflow (e.g. `abs.cpi`).
 */
export type DataflowId = string;

export type DataflowsQueryFrequency = null | Frequency;

export type DataflowsQuerySource = null | SourceId;

/**
 * Query parameters for `GET /v1/dataflows`.
 */
export interface DataflowsQuery {
  frequency?: DataflowsQueryFrequency;
  source?: DataflowsQuerySource;
}

/**
 * Response envelope for `GET /v1/dataflows`.
 */
export interface DataflowsResponse {
  /** Matching dataflows, ordered by source then dataflow id. */
  dataflows: Dataflow[];
}

export type DimensionDescription = string | null;

/**
 * A single dimension within a dataflow. Binds a dimension id to a codelist
that enumerates the permitted values.
 */
export interface Dimension {
  codelist_id: CodelistId;
  description?: DimensionDescription;
  id: DimensionId;
  name: string;
  /**
   * Position of this dimension in the dataflow's canonical dimension order.
Adapters must emit dimensions in this order so series-key derivation is
stable across codebases (see `Spec.md § Data model`).
   * @minimum 0
   */
  position: number;
}

/**
 * Identifier for a dimension within a dataflow (e.g. `region`).
 */
export type DimensionId = string;

/**
 * Direction used to normalize raw indicator values.
 */
export type Direction = typeof Direction[keyof typeof Direction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Direction = {
  higher_is_better: 'higher_is_better',
  lower_is_better: 'lower_is_better',
} as const;

/**
 * Cadence at which a dataflow publishes new observations. Informational —
used by the scheduler to pick discovery intervals and by the SLO alerting
rule `dataflow-no-new-observations`.
 */
export type Frequency = typeof Frequency[keyof typeof Frequency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Frequency = {
  daily: 'daily',
  weekly: 'weekly',
  monthly: 'monthly',
  quarterly: 'quarterly',
  annual: 'annual',
  irregular: 'irregular',
} as const;

/**
 * Health endpoint response.
 */
export interface HealthResponse {
  /** Current service health. */
  status: string;
}

/**
 * Exact dimension selector for the intended APS series.
 */
export type IndicatorConfigDimensionSelector = {[key: string]: string};

/**
 * Static config for one APS indicator.
 */
export interface IndicatorConfig {
  /** APS axis. */
  axis: Axis;
  /** Expected update cadence. */
  cadence: string;
  /** Display grouping within the axis. */
  component: string;
  /** Confidence for this input. */
  confidence: Confidence;
  /** Default configured coverage status. */
  coverage_status: CoverageStatus;
  /** User-facing indicator description. */
  description: string;
  /** Exact dimension selector for the intended APS series. */
  dimension_selector?: IndicatorConfigDimensionSelector;
  /** Direction-aware normalization rule. */
  direction: Direction;
  /** User-facing indicator label. */
  display_label: string;
  /** Stable indicator id. */
  indicator_id: string;
  /** Source measure id. */
  measure_id: string;
  /** Normalization references. */
  normalization: Normalization;
  /** Source and licensing metadata. */
  provenance: Provenance;
  /** Canonical source dataflow id. */
  source_dataflow_id: string;
  /** Display unit. */
  unit: string;
  /** Scored weight within the axis. Visible-unscored inputs may use zero. */
  weight: number;
}

/**
 * Dimension selector used for this input.
 */
export type IndicatorContributionDimensions = {[key: string]: string};

/**
 * Latest resolved period, when available.
 */
export type IndicatorContributionLatestPeriod = string | null;

/**
 * Normalized value in the axis scale, when scored.
 */
export type IndicatorContributionNormalizedValue = number | null;

/**
 * Optional notes.
 */
export type IndicatorContributionNotes = string | null;

/**
 * Raw observation value, when resolved.
 */
export type IndicatorContributionRawValue = number | null;

/**
 * Resolved series key, when available.
 */
export type IndicatorContributionSeriesKey = string | null;

/**
 * Resolved source artifact id, when available.
 */
export type IndicatorContributionSourceArtifactId = string | null;

/**
 * Contribution row for one indicator.
 */
export interface IndicatorContribution {
  /** Attribution metadata. */
  attribution: string;
  /** APS axis. */
  axis: Axis;
  /** Component name. */
  component: string;
  /** Contribution confidence. */
  confidence: Confidence;
  /** Coverage status. */
  coverage_status: CoverageStatus;
  /** Dimension selector used for this input. */
  dimensions: IndicatorContributionDimensions;
  /** Normalization direction. */
  direction: Direction;
  /** Indicator id. */
  indicator_id: string;
  /** Indicator label. */
  label: string;
  /** Latest resolved period, when available. */
  latest_period?: IndicatorContributionLatestPeriod;
  /** License metadata. */
  license: string;
  /** Source measure id. */
  measure_id: string;
  /** Normalized value in the axis scale, when scored. */
  normalized_value?: IndicatorContributionNormalizedValue;
  /** Optional notes. */
  notes?: IndicatorContributionNotes;
  /** Raw observation value, when resolved. */
  raw_value?: IndicatorContributionRawValue;
  /** Resolved series key, when available. */
  series_key?: IndicatorContributionSeriesKey;
  /** Resolved source artifact id, when available. */
  source_artifact_id?: IndicatorContributionSourceArtifactId;
  /** Source dataflow id. */
  source_dataflow_id: string;
  /** Source URL. */
  source_url: string;
  /** Display unit. */
  unit: string;
  /** Configured weight. */
  weight: number;
}

/**
 * Escape hatch for licenses not yet enumerated. Carries the SPDX-style id.
 */
export type LicenseOneOf = {
  /** Escape hatch for licenses not yet enumerated. Carries the SPDX-style id. */
  other: string;
};

/**
 * Canonical license identifier. Ingestion refuses to load a dataflow whose
`license` field is absent (see `Spec.md § Data licensing and attribution`).
 */
export type License = 'CC-BY-4.0' | 'CC-BY-ND-4.0' | 'CC-BY-SA-4.0' | 'public-domain' | LicenseOneOf;

/**
 * Identifier for a measure (e.g. `unemployment_rate`).
 */
export type MeasureId = string;

/**
 * Linear normalization references for one indicator.
 */
export interface Normalization {
  /** Best reference value for this indicator. */
  best: number;
  /** Worst reference value for this indicator. */
  worst: number;
}

/**
 * Free-form attributes attached to this observation (e.g. SDMX `OBS_STATUS`
or adapter-specific annotations).
 */
export type ObservationAttributes = {[key: string]: string};

/**
 * `None` when `status = Missing`.
 */
export type ObservationValue = number | null;

/**
 * One observation — a single row in the `observations` hypertable.
 */
export interface Observation {
  /** Free-form attributes attached to this observation (e.g. SDMX `OBS_STATUS`
or adapter-specific annotations). */
  attributes: ObservationAttributes;
  ingested_at: string;
  /**
   * `0` for the original publication; `N` for the Nth revision.
   * @minimum 0
   */
  revision_no: number;
  series_key: SeriesKey;
  source_artifact_id: ArtifactId;
  status: ObservationStatus;
  time: string;
  time_precision: TimePrecision;
  /** `None` when `status = Missing`. */
  value?: ObservationValue;
}

/**
 * Observation status flags sourced from SDMX. Subset in use across Australian
publishers; extend as new codes appear in upstream feeds.
 */
export type ObservationStatus = typeof ObservationStatus[keyof typeof ObservationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ObservationStatus = {
  normal: 'normal',
  estimated: 'estimated',
  forecast: 'forecast',
  imputed: 'imputed',
  missing: 'missing',
  provisional: 'provisional',
  revised: 'revised',
  break: 'break',
} as const;

/**
 * Attribution and licensing metadata that applies to an observations page.
 */
export interface ObservationsMetadata {
  /** Required source acknowledgement to display with derived charts. */
  attribution: string;
  /** Requested dataflow identifier. */
  dataflow: DataflowId;
  /** Data license identifier, e.g. `CC-BY-4.0`. */
  license: string;
  /** Canonical citation URL for the upstream source. */
  source_url: string;
}

/**
 * JSON response envelope for `/v1/observations`.
 */
export interface ObservationsResponse {
  /** Dataflow attribution and license metadata. */
  metadata: ObservationsMetadata;
  /** Observation rows in ascending `(time, series_key)` order. */
  observations: ObservationsRow[];
  /** Cursor for continuing the query. */
  pagination: PaginationMetadata;
}

/**
 * Free-form source attributes for this observation.
 */
export type ObservationsRowAttributes = {[key: string]: string};

/**
 * Series dimension values keyed by dimension id.
 */
export type ObservationsRowDimensions = {[key: string]: string};

/**
 * Numeric value; null when status is `missing`.
 */
export type ObservationsRowValue = number | null;

/**
 * One observation row returned by `/v1/observations`.
 */
export interface ObservationsRow {
  /** Free-form source attributes for this observation. */
  attributes: ObservationsRowAttributes;
  /** Series dimension values keyed by dimension id. */
  dimensions: ObservationsRowDimensions;
  /** Ingestion timestamp for this revision. */
  ingested_at: string;
  /** Measure identifier for the series. */
  measure_id: string;
  /**
   * Revision number, where zero is the original publication.
   * @minimum 0
   */
  revision_no: number;
  /** Deterministic series key. */
  series_key: SeriesKey;
  /** Content-addressed source artifact identifier. */
  source_artifact_id: ArtifactId;
  /** Observation status. */
  status: ObservationStatus;
  /** Observation timestamp. */
  time: string;
  /** Temporal precision of the timestamp. */
  time_precision: TimePrecision;
  /** Unit for the series values. */
  unit: string;
  /** Numeric value; null when status is `missing`. */
  value?: ObservationsRowValue;
}

/**
 * Opaque cursor for the next page, or null when the page is complete.
 */
export type PaginationMetadataNextCursor = string | null;

/**
 * Cursor metadata for the current observations page.
 */
export interface PaginationMetadata {
  /** Opaque cursor for the next page, or null when the page is complete. */
  next_cursor?: PaginationMetadataNextCursor;
}

/**
 * Request-specific detail, if any.
 */
export type ProblemDetailsDetail = string | null;

/**
 * Resource-specific identifier, if any.
 */
export type ProblemDetailsInstance = string | null;

/**
 * RFC 7807 problem details body.
 */
export interface ProblemDetails {
  /** Request-specific detail, if any. */
  detail?: ProblemDetailsDetail;
  /** Resource-specific identifier, if any. */
  instance?: ProblemDetailsInstance;
  /**
   * HTTP status code for this problem.
   * @minimum 0
   */
  status: number;
  /** Short, human-readable summary. */
  title: string;
  /** Problem type URI. */
  type: string;
}

/**
 * Optional source or review notes.
 */
export type ProvenanceNotes = string | null;

/**
 * Optional retrieval date for curated/manual inputs.
 */
export type ProvenanceRetrievedAt = string | null;

/**
 * Optional review date for curated/manual inputs.
 */
export type ProvenanceReviewedAt = string | null;

/**
 * Optional reviewer identifier for curated/manual inputs.
 */
export type ProvenanceReviewedBy = string | null;

/**
 * Source and licensing metadata for a scorecard input.
 */
export interface Provenance {
  /** Attribution text shown in API/UI responses. */
  attribution: string;
  /** License identifier or source-specific license note. */
  license: string;
  /** Optional source or review notes. */
  notes?: ProvenanceNotes;
  /** Optional retrieval date for curated/manual inputs. */
  retrieved_at?: ProvenanceRetrievedAt;
  /** Optional review date for curated/manual inputs. */
  reviewed_at?: ProvenanceReviewedAt;
  /** Optional reviewer identifier for curated/manual inputs. */
  reviewed_by?: ProvenanceReviewedBy;
  /** Canonical source URL for this input. */
  source_url: string;
}

/**
 * APS score zone.
 */
export type ScoreZone = typeof ScoreZone[keyof typeof ScoreZone];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScoreZone = {
  red: 'red',
  yellow: 'yellow',
  green: 'green',
} as const;

/**
 * APS config metadata and indicator list.
 */
export interface ScorecardConfig {
  /** Attribution note for the derived scorecard config. */
  attribution: string;
  /** User-facing description. */
  description: string;
  /** Formula metadata. */
  formula: string;
  /** Scorecard id. */
  id: string;
  /** Indicator definitions. */
  indicators: IndicatorConfig[];
  /** User-facing label. */
  label: string;
  /** License note for the derived scorecard config. */
  license: string;
  /** Versioned config id. */
  version: string;
}

/**
 * Inclusive lower snapshot date in `YYYY-MM-DD` form.
 */
export type ScorecardHistoryQuerySince = string | null;

/**
 * Inclusive upper snapshot date in `YYYY-MM-DD` form.
 */
export type ScorecardHistoryQueryUntil = string | null;

/**
 * Query string for APS history snapshots.
 */
export interface ScorecardHistoryQuery {
  /** Inclusive lower snapshot date in `YYYY-MM-DD` form. */
  since?: ScorecardHistoryQuerySince;
  /** Inclusive upper snapshot date in `YYYY-MM-DD` form. */
  until?: ScorecardHistoryQueryUntil;
}

/**
 * Latest period represented by resolved inputs.
 */
export type ScorecardSnapshotLatestPeriod = string | null;

/**
 * Full APS snapshot produced by the pure scorer.
 */
export interface ScorecardSnapshot {
  /** Snapshot timestamp or date chosen by the caller. */
  as_of: string;
  /** Snapshot confidence label. */
  confidence: Confidence;
  /** Worst/best APS confidence band. */
  confidence_band: ConfidenceBand;
  /** Config version used for the score. */
  config_version: string;
  /** Indicator-level contribution rows. */
  contributions: IndicatorContribution[];
  /** Weight-aware coverage percentage. */
  coverage_pct: number;
  /** Latest period represented by resolved inputs. */
  latest_period?: ScorecardSnapshotLatestPeriod;
  /** APS score in `0..100`. */
  score: number;
  /** Scorecard id. */
  scorecard_id: string;
  /** Axis-level scores. */
  sub_indexes: SubIndexScore[];
  /** Trend relative to prior comparable score. */
  trend: Trend;
  /** Score zone. */
  zone: ScoreZone;
}

/**
 * Maximum number of catalog results to return.
 * @minimum 0
 */
export type SearchQueryLimit = number | null;

/**
 * Query parameters for `GET /v1/search`.
 */
export interface SearchQuery {
  /**
   * Maximum number of catalog results to return.
   * @minimum 0
   */
  limit?: SearchQueryLimit;
  /** Search text. Blank queries are rejected. */
  q: string;
}

/**
 * Response envelope for `GET /v1/search`.
 */
export interface SearchResponse {
  /** Normalized query text used for ranking. */
  query: string;
  /** Ranked catalog matches. */
  results: SearchResult[];
}

/**
 * Optional catalog description.
 */
export type SearchResultDescription = string | null;

export type SearchResultSourceId = null | SourceId;

/**
 * A ranked catalog search result.
 */
export interface SearchResult {
  /** Dataflows directly represented by this match. */
  dataflow_ids: DataflowId[];
  /** Optional catalog description. */
  description?: SearchResultDescription;
  /** Stable catalog identifier. */
  id: string;
  /** Matched catalog object type. */
  kind: SearchResultKind;
  /** Human-readable name. */
  name: string;
  /** Relevance score. Larger scores rank first. */
  score: number;
  source_id?: SearchResultSourceId;
}

/**
 * Catalog object types returned by search.
 */
export type SearchResultKind = typeof SearchResultKind[keyof typeof SearchResultKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchResultKind = {
  dataflow: 'dataflow',
  measure: 'measure',
} as const;

/**
 * Dimension values keyed by typed dimension ids and code ids. Stored
sorted (via `BTreeMap`) so iteration order is stable across
serialisation + re-hashing.
 */
export type SeriesDimensions = {[key: string]: CodeId};

export type SeriesFirstObserved = string | null;

export type SeriesLastObserved = string | null;

/**
 * One time series within a dataflow. `dimensions` is the sorted bag of
`(key, value)` pairs that, together with `dataflow_id` and `measure_id`,
seeds `series_key`.
 */
export interface Series {
  /** Whether the upstream source still publishes this series. Inactive
series are retained for historical queries but excluded from the
default `/v1/series` listing. */
  active: boolean;
  dataflow_id: DataflowId;
  /** Dimension values keyed by typed dimension ids and code ids. Stored
sorted (via `BTreeMap`) so iteration order is stable across
serialisation + re-hashing. */
  dimensions: SeriesDimensions;
  first_observed?: SeriesFirstObserved;
  last_observed?: SeriesLastObserved;
  measure_id: MeasureId;
  series_key: SeriesKey;
  unit: string;
}

/**
 * Lowercase hex-encoded SHA-256 digest (64 chars).
 * @minLength 64
 * @maxLength 64
 */
export type SeriesKey = string;

export type SeriesLookupResponseLatestObservation = null | Observation;

export type SeriesLookupResponseRevision = null | SeriesRevisionMetadata;

/**
 * Response envelope for `GET /v1/series/{dataflow}/{series_key}`.
 */
export interface SeriesLookupResponse {
  latest_observation?: SeriesLookupResponseLatestObservation;
  revision?: SeriesLookupResponseRevision;
  /** Series metadata. */
  series: Series;
}

/**
 * Revision details for the latest observation returned with a series lookup.
 */
export interface SeriesRevisionMetadata {
  /** When this revision was ingested. */
  ingested_at: string;
  /** Whether this observation supersedes the original publication. */
  is_revision: boolean;
  /**
   * Latest revision number for the observation timestamp.
   * @minimum 0
   */
  revision_no: number;
  /** Source artifact that produced this revision. */
  source_artifact_id: ArtifactId;
}

/**
 * Repository-relative representative fixture or reviewed snapshot.
 */
export type SourceCatalogDataflowFixtureReference = string | null;

export type SourceCatalogDataflowFreshnessPolicy = null | SourceFreshnessPolicy;

/**
 * Accountable production role, when assigned.
 */
export type SourceCatalogDataflowOwnerRole = string | null;

export type SourceCatalogDataflowRequestPolicy = null | SourceRequestPolicy;

export type SourceCatalogDataflowSchedule = null | SourceSchedule;

export type SourceCatalogDataflowValidationPolicy = null | SourceValidationPolicy;

/**
 * Governed source-dataflow metadata.
 */
export interface SourceCatalogDataflow {
  /** Required attribution. */
  attribution: string;
  /** Expected source cadence. */
  cadence: string;
  /** Coverage state exposed to catalog consumers. */
  coverage_state: string;
  /** Stable dataflow id. */
  dataflow_id: string;
  /** Repository-relative representative fixture or reviewed snapshot. */
  fixture_reference?: SourceCatalogDataflowFixtureReference;
  freshness_policy?: SourceCatalogDataflowFreshnessPolicy;
  /** Source licence or terms identifier. */
  license: string;
  /** Owning implementation area. */
  owner_area: string;
  /** Accountable production role, when assigned. */
  owner_role?: SourceCatalogDataflowOwnerRole;
  request_policy?: SourceCatalogDataflowRequestPolicy;
  schedule?: SourceCatalogDataflowSchedule;
  /** Canonical source and citation URL. */
  source_url: string;
  /** Source-register governance status. */
  status: string;
  validation_policy?: SourceCatalogDataflowValidationPolicy;
}

/**
 * One source and its governed dataflows.
 */
export interface SourceCatalogEntry {
  /** Dataflows governed for this source. */
  dataflows: SourceCatalogDataflow[];
  /** Stable source id. */
  source_id: string;
}

/**
 * Public source freshness policy.
 */
export interface SourceFreshnessPolicy {
  /**
   * Age in seconds after which data is hard-expired.
   * @minimum 0
   */
  hard_after_seconds: number;
  /**
   * Age in seconds after which data is soft-stale.
   * @minimum 0
   */
  soft_after_seconds: number;
}

/**
 * Identifier for an upstream data source (e.g. `abs`, `rba`, `apra`).
 */
export type SourceId = string;

/**
 * Public upstream request policy.
 */
export interface SourceRequestPolicy {
  /**
   * Maximum short request burst.
   * @minimum 0
   */
  burst: number;
  /**
   * Maximum steady-state requests per minute.
   * @minimum 0
   */
  max_requests_per_minute: number;
  /**
   * Per-request timeout in seconds.
   * @minimum 0
   */
  timeout_seconds: number;
}

/**
 * Public source discovery schedule.
 */
export interface SourceSchedule {
  /** Five-field cron expression. */
  cron: string;
  /** IANA timezone name. */
  timezone: string;
}

/**
 * Public source validation policy.
 */
export interface SourceValidationPolicy {
  /** Whether partial rows may publish. */
  allow_partial_rows: boolean;
  /**
   * Maximum series cardinality for one generation.
   * @minimum 0
   */
  max_series_cardinality: number;
  /** Named adapter range rule. */
  range_rule: string;
}

/**
 * Response envelope for `GET /v1/sources`.
 */
export interface SourcesResponse {
  /** Governed sources ordered by source id. */
  sources: SourceCatalogEntry[];
}

/**
 * Axis-level sub-index score.
 */
export interface SubIndexScore {
  /** Axis name. */
  axis: Axis;
  /** Component scores for this axis. */
  components: ComponentScore[];
  /** Axis confidence band in the axis scale. */
  confidence_band: ConfidenceBand;
  /** Weight-aware coverage percentage. */
  coverage_pct: number;
  /** Axis score (`0..1` for throughput, `-1..1` for orientation). */
  score: number;
  /** Expected scored weight for this axis. */
  weight: number;
}

/**
 * Created webhook subscription details.
 */
export interface SubscriptionDetails {
  /** UTC creation timestamp. */
  created_at: string;
  /** Dataflow filter attached to the subscription. */
  dataflow_ids: DataflowId[];
  /** Stable subscription id. */
  id: string;
  /** HMAC signing secret shown once at creation. */
  signing_secret: string;
  /** Current subscription status. */
  status: string;
  /** Delivery target URL. */
  url: string;
}

/**
 * Temporal granularity of an observation's timestamp. Matches the SDMX
`@FREQ` facet on a coarse scale.
 */
export type TimePrecision = typeof TimePrecision[keyof typeof TimePrecision];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimePrecision = {
  minute: 'minute',
  day: 'day',
  week: 'week',
  month: 'month',
  quarter: 'quarter',
  year: 'year',
} as const;

/**
 * Trend arrow comparing the latest score to a prior comparable snapshot.
 */
export type Trend = typeof Trend[keyof typeof Trend];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Trend = {
  up: 'up',
  down: 'down',
  flat: 'flat',
  unavailable: 'unavailable',
} as const;

export type ListDataflowsParams = {
/**
 * Optional source id filter, e.g. abs.
 * @minLength 1
 * @maxLength 128
 */
source?: string;
/**
 * Optional publication frequency filter.
 * @minLength 1
 * @pattern ^(annual|quarterly|monthly|weekly|daily|irregular)$
 */
frequency?: string;
};

export type ListObservationsParams = {
/**
 * Required dataflow id, e.g. abs.cpi.
 * @minLength 1
 * @maxLength 128
 */
dataflow: string;
/**
 * Dimension filters as repeated key=value values. The handler also accepts dimensions[region]=AUS.
 */
'dimensions[]'?: string[];
/**
 * Inclusive lower time bound as YYYY-MM-DD or RFC3339.
 * @minLength 1
 */
since?: string;
/**
 * Inclusive upper time bound as YYYY-MM-DD or RFC3339.
 * @minLength 1
 */
until?: string;
/**
 * Optional dataflow frequency filter, or weekly/monthly/quarterly rollup grain.
 * @minLength 1
 * @pattern ^(annual|quarterly|monthly|weekly|daily|irregular)$
 */
frequency?: string;
/**
 * Response format: json, csv, or parquet.
 * @minLength 3
 * @maxLength 7
 * @pattern ^(json|csv|parquet)$
 */
format?: string;
/**
 * Opaque cursor from the previous page.
 * @minLength 1
 */
cursor?: string;
/**
 * Page size. JSON/CSV are capped at 10000 rows; Parquet bulk exports are capped at 1000000 rows.
 * @minimum 0
 * @maximum 1000000
 */
limit?: number;
};

export type Openapi200 = { [key: string]: unknown };

export type ListApsScorecardHistoryParams = {
/**
 * Inclusive lower snapshot date in `YYYY-MM-DD` form.
 */
since?: string | null;
/**
 * Inclusive upper snapshot date in `YYYY-MM-DD` form.
 */
until?: string | null;
};

export type SearchCatalogParams = {
/**
 * Search text.
 * @minLength 1
 */
q: string;
/**
 * Maximum number of results, capped at 100.
 * @minimum 0
 * @maximum 65535
 */
limit?: number;
};

/**
 * @summary `GET /v1/dataflows`.
 */
export type listDataflowsResponse200 = {
  data: DataflowsResponse
  status: 200
}

export type listDataflowsResponse400 = {
  data: ProblemDetails
  status: 400
}

export type listDataflowsResponse500 = {
  data: ProblemDetails
  status: 500
}

export type listDataflowsResponseSuccess = (listDataflowsResponse200) & {
  headers: Headers;
};
export type listDataflowsResponseError = (listDataflowsResponse400 | listDataflowsResponse500) & {
  headers: Headers;
};

export type listDataflowsResponse = (listDataflowsResponseSuccess | listDataflowsResponseError)

export const getListDataflowsUrl = (params?: ListDataflowsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/dataflows?${stringifiedParams}` : `/v1/dataflows`
}

export const listDataflows = async (params?: ListDataflowsParams, options?: RequestInit): Promise<listDataflowsResponse> => {

  const res = await fetch(getListDataflowsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listDataflowsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listDataflowsResponse
}



/**
 * @summary `GET /v1/dataflows/{id}`.
 */
export type getDataflowResponse200 = {
  data: DataflowDetailResponse
  status: 200
}

export type getDataflowResponse400 = {
  data: ProblemDetails
  status: 400
}

export type getDataflowResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getDataflowResponse500 = {
  data: ProblemDetails
  status: 500
}

export type getDataflowResponseSuccess = (getDataflowResponse200) & {
  headers: Headers;
};
export type getDataflowResponseError = (getDataflowResponse400 | getDataflowResponse404 | getDataflowResponse500) & {
  headers: Headers;
};

export type getDataflowResponse = (getDataflowResponseSuccess | getDataflowResponseError)

export const getGetDataflowUrl = (id: string,) => {




  return `/v1/dataflows/${id}`
}

export const getDataflow = async (id: string, options?: RequestInit): Promise<getDataflowResponse> => {

  const res = await fetch(getGetDataflowUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getDataflowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDataflowResponse
}



/**
 * @summary `GET /v1/dataflows/{id}/codelists/{dim}`.
 */
export type getDataflowCodelistResponse200 = {
  data: DataflowCodelistResponse
  status: 200
}

export type getDataflowCodelistResponse400 = {
  data: ProblemDetails
  status: 400
}

export type getDataflowCodelistResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getDataflowCodelistResponse500 = {
  data: ProblemDetails
  status: 500
}

export type getDataflowCodelistResponseSuccess = (getDataflowCodelistResponse200) & {
  headers: Headers;
};
export type getDataflowCodelistResponseError = (getDataflowCodelistResponse400 | getDataflowCodelistResponse404 | getDataflowCodelistResponse500) & {
  headers: Headers;
};

export type getDataflowCodelistResponse = (getDataflowCodelistResponseSuccess | getDataflowCodelistResponseError)

export const getGetDataflowCodelistUrl = (id: string,
    dim: string,) => {




  return `/v1/dataflows/${id}/codelists/${dim}`
}

export const getDataflowCodelist = async (id: string,
    dim: string, options?: RequestInit): Promise<getDataflowCodelistResponse> => {

  const res = await fetch(getGetDataflowCodelistUrl(id,dim),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getDataflowCodelistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDataflowCodelistResponse
}



/**
 * @summary `GET /v1/health`.
 */
export type healthResponse200 = {
  data: HealthResponse
  status: 200
}

export type healthResponse408 = {
  data: ProblemDetails
  status: 408
}

export type healthResponseSuccess = (healthResponse200) & {
  headers: Headers;
};
export type healthResponseError = (healthResponse408) & {
  headers: Headers;
};

export type healthResponse = (healthResponseSuccess | healthResponseError)

export const getHealthUrl = () => {




  return `/v1/health`
}

export const health = async ( options?: RequestInit): Promise<healthResponse> => {

  const res = await fetch(getHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthResponse
}



/**
 * @summary `GET /v1/observations`.
 */
export type listObservationsResponse200ApplicationJson = {
  data: ObservationsResponse
  status: 200
}

export type listObservationsResponse200TextCsv = {
  data: string
  status: 200
}

export type listObservationsResponse304 = {
  data: void
  status: 304
}

export type listObservationsResponse400 = {
  data: ProblemDetails
  status: 400
}

export type listObservationsResponse404 = {
  data: ProblemDetails
  status: 404
}

export type listObservationsResponse408 = {
  data: ProblemDetails
  status: 408
}

export type listObservationsResponse500 = {
  data: ProblemDetails
  status: 500
}

export type listObservationsResponseSuccess = (listObservationsResponse200ApplicationJson | listObservationsResponse200TextCsv) & {
  headers: Headers;
};
export type listObservationsResponseError = (listObservationsResponse304 | listObservationsResponse400 | listObservationsResponse404 | listObservationsResponse408 | listObservationsResponse500) & {
  headers: Headers;
};

export type listObservationsResponse = (listObservationsResponseSuccess | listObservationsResponseError)

export const getListObservationsUrl = (params: ListObservationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["dimensions[]"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/observations?${stringifiedParams}` : `/v1/observations`
}

export const listObservations = async (params: ListObservationsParams, options?: RequestInit): Promise<listObservationsResponse> => {

  const res = await fetch(getListObservationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listObservationsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listObservationsResponse
}



/**
 * @summary `GET /v1/openapi.json`.
 */
export type openapiResponse200 = {
  data: Openapi200
  status: 200
}

export type openapiResponse408 = {
  data: ProblemDetails
  status: 408
}

export type openapiResponse500 = {
  data: ProblemDetails
  status: 500
}

export type openapiResponseSuccess = (openapiResponse200) & {
  headers: Headers;
};
export type openapiResponseError = (openapiResponse408 | openapiResponse500) & {
  headers: Headers;
};

export type openapiResponse = (openapiResponseSuccess | openapiResponseError)

export const getOpenapiUrl = () => {




  return `/v1/openapi.json`
}

export const openapi = async ( options?: RequestInit): Promise<openapiResponse> => {

  const res = await fetch(getOpenapiUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: openapiResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as openapiResponse
}



/**
 * @summary `GET /v1/scorecards/aps/config`.
 */
export type getApsScorecardConfigResponse200 = {
  data: ScorecardConfig
  status: 200
}

export type getApsScorecardConfigResponse304 = {
  data: void
  status: 304
}

export type getApsScorecardConfigResponse500 = {
  data: ProblemDetails
  status: 500
}

export type getApsScorecardConfigResponseSuccess = (getApsScorecardConfigResponse200) & {
  headers: Headers;
};
export type getApsScorecardConfigResponseError = (getApsScorecardConfigResponse304 | getApsScorecardConfigResponse500) & {
  headers: Headers;
};

export type getApsScorecardConfigResponse = (getApsScorecardConfigResponseSuccess | getApsScorecardConfigResponseError)

export const getGetApsScorecardConfigUrl = () => {




  return `/v1/scorecards/aps/config`
}

export const getApsScorecardConfig = async ( options?: RequestInit): Promise<getApsScorecardConfigResponse> => {

  const res = await fetch(getGetApsScorecardConfigUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApsScorecardConfigResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApsScorecardConfigResponse
}



/**
 * @summary `GET /v1/scorecards/aps/history`.
 */
export type listApsScorecardHistoryResponse200 = {
  data: ScorecardSnapshot[]
  status: 200
}

export type listApsScorecardHistoryResponse304 = {
  data: void
  status: 304
}

export type listApsScorecardHistoryResponse400 = {
  data: ProblemDetails
  status: 400
}

export type listApsScorecardHistoryResponse500 = {
  data: ProblemDetails
  status: 500
}

export type listApsScorecardHistoryResponseSuccess = (listApsScorecardHistoryResponse200) & {
  headers: Headers;
};
export type listApsScorecardHistoryResponseError = (listApsScorecardHistoryResponse304 | listApsScorecardHistoryResponse400 | listApsScorecardHistoryResponse500) & {
  headers: Headers;
};

export type listApsScorecardHistoryResponse = (listApsScorecardHistoryResponseSuccess | listApsScorecardHistoryResponseError)

export const getListApsScorecardHistoryUrl = (params?: ListApsScorecardHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/scorecards/aps/history?${stringifiedParams}` : `/v1/scorecards/aps/history`
}

export const listApsScorecardHistory = async (params?: ListApsScorecardHistoryParams, options?: RequestInit): Promise<listApsScorecardHistoryResponse> => {

  const res = await fetch(getListApsScorecardHistoryUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listApsScorecardHistoryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listApsScorecardHistoryResponse
}



/**
 * @summary `GET /v1/scorecards/aps/latest`.
 */
export type getApsScorecardLatestResponse200 = {
  data: ScorecardSnapshot
  status: 200
}

export type getApsScorecardLatestResponse304 = {
  data: void
  status: 304
}

export type getApsScorecardLatestResponse500 = {
  data: ProblemDetails
  status: 500
}

export type getApsScorecardLatestResponseSuccess = (getApsScorecardLatestResponse200) & {
  headers: Headers;
};
export type getApsScorecardLatestResponseError = (getApsScorecardLatestResponse304 | getApsScorecardLatestResponse500) & {
  headers: Headers;
};

export type getApsScorecardLatestResponse = (getApsScorecardLatestResponseSuccess | getApsScorecardLatestResponseError)

export const getGetApsScorecardLatestUrl = () => {




  return `/v1/scorecards/aps/latest`
}

export const getApsScorecardLatest = async ( options?: RequestInit): Promise<getApsScorecardLatestResponse> => {

  const res = await fetch(getGetApsScorecardLatestUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApsScorecardLatestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApsScorecardLatestResponse
}



/**
 * @summary `GET /v1/search`.
 */
export type searchCatalogResponse200 = {
  data: SearchResponse
  status: 200
}

export type searchCatalogResponse400 = {
  data: ProblemDetails
  status: 400
}

export type searchCatalogResponse500 = {
  data: ProblemDetails
  status: 500
}

export type searchCatalogResponseSuccess = (searchCatalogResponse200) & {
  headers: Headers;
};
export type searchCatalogResponseError = (searchCatalogResponse400 | searchCatalogResponse500) & {
  headers: Headers;
};

export type searchCatalogResponse = (searchCatalogResponseSuccess | searchCatalogResponseError)

export const getSearchCatalogUrl = (params: SearchCatalogParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/search?${stringifiedParams}` : `/v1/search`
}

export const searchCatalog = async (params: SearchCatalogParams, options?: RequestInit): Promise<searchCatalogResponse> => {

  const res = await fetch(getSearchCatalogUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchCatalogResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchCatalogResponse
}



/**
 * @summary `GET /v1/series/{dataflow}/{series_key}`.
 */
export type getSeriesResponse200 = {
  data: SeriesLookupResponse
  status: 200
}

export type getSeriesResponse400 = {
  data: ProblemDetails
  status: 400
}

export type getSeriesResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getSeriesResponse500 = {
  data: ProblemDetails
  status: 500
}

export type getSeriesResponseSuccess = (getSeriesResponse200) & {
  headers: Headers;
};
export type getSeriesResponseError = (getSeriesResponse400 | getSeriesResponse404 | getSeriesResponse500) & {
  headers: Headers;
};

export type getSeriesResponse = (getSeriesResponseSuccess | getSeriesResponseError)

export const getGetSeriesUrl = (dataflow: string,
    seriesKey: string,) => {




  return `/v1/series/${dataflow}/${seriesKey}`
}

export const getSeries = async (dataflow: string,
    seriesKey: string, options?: RequestInit): Promise<getSeriesResponse> => {

  const res = await fetch(getGetSeriesUrl(dataflow,seriesKey),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSeriesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSeriesResponse
}



/**
 * @summary `GET /v1/sources`.
 */
export type listSourcesResponse200 = {
  data: SourcesResponse
  status: 200
}

export type listSourcesResponse500 = {
  data: ProblemDetails
  status: 500
}

export type listSourcesResponseSuccess = (listSourcesResponse200) & {
  headers: Headers;
};
export type listSourcesResponseError = (listSourcesResponse500) & {
  headers: Headers;
};

export type listSourcesResponse = (listSourcesResponseSuccess | listSourcesResponseError)

export const getListSourcesUrl = () => {




  return `/v1/sources`
}

export const listSources = async ( options?: RequestInit): Promise<listSourcesResponse> => {

  const res = await fetch(getListSourcesUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listSourcesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listSourcesResponse
}



/**
 * @summary `GET /v1/sources/{source_id}`.
 */
export type getSourceResponse200 = {
  data: SourceCatalogEntry
  status: 200
}

export type getSourceResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getSourceResponse500 = {
  data: ProblemDetails
  status: 500
}

export type getSourceResponseSuccess = (getSourceResponse200) & {
  headers: Headers;
};
export type getSourceResponseError = (getSourceResponse404 | getSourceResponse500) & {
  headers: Headers;
};

export type getSourceResponse = (getSourceResponseSuccess | getSourceResponseError)

export const getGetSourceUrl = (sourceId: string,) => {




  return `/v1/sources/${sourceId}`
}

export const getSource = async (sourceId: string, options?: RequestInit): Promise<getSourceResponse> => {

  const res = await fetch(getGetSourceUrl(sourceId),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSourceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSourceResponse
}



/**
 * @summary `POST /v1/subscriptions`.
 */
export type createSubscriptionResponse201 = {
  data: CreateSubscriptionResponse
  status: 201
}

export type createSubscriptionResponse400 = {
  data: ProblemDetails
  status: 400
}

export type createSubscriptionResponse401 = {
  data: ProblemDetails
  status: 401
}

export type createSubscriptionResponse500 = {
  data: ProblemDetails
  status: 500
}

export type createSubscriptionResponseSuccess = (createSubscriptionResponse201) & {
  headers: Headers;
};
export type createSubscriptionResponseError = (createSubscriptionResponse400 | createSubscriptionResponse401 | createSubscriptionResponse500) & {
  headers: Headers;
};

export type createSubscriptionResponse = (createSubscriptionResponseSuccess | createSubscriptionResponseError)

export const getCreateSubscriptionUrl = () => {




  return `/v1/subscriptions`
}

export const createSubscription = async (createSubscriptionRequest: CreateSubscriptionRequest, options?: RequestInit): Promise<createSubscriptionResponse> => {

  const res = await fetch(getCreateSubscriptionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSubscriptionRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createSubscriptionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createSubscriptionResponse
}
