/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Australian KPIs API
 * Unified API for Australian public economic data.
 * OpenAPI spec version: 0.1.0
 */
/**
 * Health endpoint response.
 */
export interface HealthResponse {
  /** Current service health. */
  status: string;
}

/**
 * Request-specific detail, if any.
 */
export type ProblemDetailsDetail = string | null;

/**
 * Resource-specific identifier, if any.
 */
export type ProblemDetailsInstance = string | null;

/**
 * RFC 7807 problem details body.
 */
export interface ProblemDetails {
  /** Request-specific detail, if any. */
  detail?: ProblemDetailsDetail;
  /** Resource-specific identifier, if any. */
  instance?: ProblemDetailsInstance;
  /**
   * HTTP status code for this problem.
   * @minimum 0
   */
  status: number;
  /** Short, human-readable summary. */
  title: string;
  /** Problem type URI. */
  type: string;
}

export type Openapi200 = { [key: string]: unknown };

/**
 * @summary `GET /v1/health`.
 */
export type healthResponse200 = {
  data: HealthResponse
  status: 200
}

export type healthResponse408 = {
  data: ProblemDetails
  status: 408
}

export type healthResponseComposite = healthResponse200 | healthResponse408;

export type healthResponse = healthResponseComposite & {
  headers: Headers;
}

export const getHealthUrl = () => {




  return `/v1/health`
}

export const health = async ( options?: RequestInit): Promise<healthResponse> => {

  const res = await fetch(getHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: healthResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as healthResponse
}



/**
 * @summary `GET /v1/openapi.json`.
 */
export type openapiResponse200 = {
  data: Openapi200
  status: 200
}

export type openapiResponse408 = {
  data: ProblemDetails
  status: 408
}

export type openapiResponseComposite = openapiResponse200 | openapiResponse408;

export type openapiResponse = openapiResponseComposite & {
  headers: Headers;
}

export const getOpenapiUrl = () => {




  return `/v1/openapi.json`
}

export const openapi = async ( options?: RequestInit): Promise<openapiResponse> => {

  const res = await fetch(getOpenapiUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: openapiResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as openapiResponse
}
