// Generated by openapi-zod-client. Do not edit manually.
import { z } from "zod";

type Code = {
  codelist_id: CodelistId;
  description?: (string | null) | undefined;
  id: CodeId;
  name: string;
  parent_id?: (null | CodeId) | undefined;
};
type CodelistId = string;
type CodeId = string;
type Codelist = {
  codes: Array<Code>;
  description?: (string | null) | undefined;
  id: CodelistId;
  name: string;
};
type CreateSubscriptionRequest = {
  dataflow_ids?: Array<DataflowId> | undefined;
  url: string;
};
type DataflowId = string;
type CreateSubscriptionResponse = {
  subscription: SubscriptionDetails;
};
type SubscriptionDetails = {
  created_at: string;
  dataflow_ids: Array<DataflowId>;
  id: string;
  signing_secret: string;
  status: string;
  url: string;
};
type Dataflow = {
  attribution: string;
  description?: (string | null) | undefined;
  dimensions: Array<DimensionId>;
  frequency: Frequency;
  id: DataflowId;
  license: License;
  measures: Array<MeasureId>;
  name: string;
  source_id: SourceId;
  source_url: string;
};
type DimensionId = string;
type Frequency =
  | "daily"
  | "weekly"
  | "monthly"
  | "quarterly"
  | "annual"
  | "irregular";
type License =
  | "CC-BY-4.0"
  | "CC-BY-ND-4.0"
  | "CC-BY-SA-4.0"
  | "public-domain"
  | {
      other: string;
    };
type MeasureId = string;
type SourceId = string;
type DataflowCodelistResponse = {
  codelist: Codelist;
  dataflow_id: DataflowId;
  dimension_id: DimensionId;
};
type Axis = "throughput" | "orientation";
type Direction = "higher_is_better" | "lower_is_better";
type Confidence = "high" | "medium" | "low";
type CoverageStatus =
  | "resolved"
  | "stale"
  | "missing_expected"
  | "coverage_gap"
  | "manual_pending"
  | "visible_unscored";
type ScoreZone = "red" | "yellow" | "green";
type Trend = "up" | "down" | "flat" | "unavailable";
type Normalization = {
  best: number;
  worst: number;
};
type Provenance = {
  attribution: string;
  license: string;
  notes?: (string | null) | undefined;
  retrieved_at?: (string | null) | undefined;
  reviewed_at?: (string | null) | undefined;
  reviewed_by?: (string | null) | undefined;
  source_url: string;
};
type IndicatorConfig = {
  axis: Axis;
  cadence: string;
  component: string;
  confidence: Confidence;
  coverage_status: CoverageStatus;
  description: string;
  dimension_selector?: Record<string, string> | undefined;
  direction: Direction;
  display_label: string;
  indicator_id: string;
  measure_id: string;
  normalization: Normalization;
  provenance: Provenance;
  source_dataflow_id: string;
  unit: string;
  weight: number;
};
type ScorecardConfig = {
  attribution: string;
  description: string;
  formula: string;
  id: string;
  indicators: Array<IndicatorConfig>;
  label: string;
  license: string;
  version: string;
};
type ConfidenceBand = {
  high: number;
  low: number;
};
type ComponentScore = {
  component: string;
  coverage_pct: number;
  score: number;
  weight: number;
};
type SubIndexScore = {
  axis: Axis;
  components: Array<ComponentScore>;
  confidence_band: ConfidenceBand;
  coverage_pct: number;
  score: number;
  weight: number;
};
type IndicatorContribution = {
  attribution: string;
  axis: Axis;
  component: string;
  confidence: Confidence;
  coverage_status: CoverageStatus;
  dimensions: Record<string, string>;
  direction: Direction;
  indicator_id: string;
  label: string;
  latest_period?: (string | null) | undefined;
  license: string;
  measure_id: string;
  normalized_value?: (number | null) | undefined;
  notes?: (string | null) | undefined;
  raw_value?: (number | null) | undefined;
  series_key?: (string | null) | undefined;
  source_artifact_id?: (string | null) | undefined;
  source_dataflow_id: string;
  source_url: string;
  unit: string;
  weight: number;
};
type ScorecardSnapshot = {
  as_of: string;
  confidence: Confidence;
  confidence_band: ConfidenceBand;
  config_version: string;
  contributions: Array<IndicatorContribution>;
  coverage_pct: number;
  latest_period?: (string | null) | undefined;
  score: number;
  scorecard_id: string;
  sub_indexes: Array<SubIndexScore>;
  trend: Trend;
  zone: ScoreZone;
};
type DataflowDetailResponse = {
  dataflow: Dataflow;
  dimensions: Array<Dimension>;
};
type Dimension = {
  codelist_id: CodelistId;
  description?: (string | null) | undefined;
  id: DimensionId;
  name: string;
  position: number;
};
type DataflowsQuery = Partial<{
  frequency: null | Frequency;
  source: null | SourceId;
}>;
type DataflowsResponse = {
  dataflows: Array<Dataflow>;
};
type Observation = {
  attributes: {};
  ingested_at: string;
  revision_no: number;
  series_key: SeriesKey;
  source_artifact_id: ArtifactId;
  status: ObservationStatus;
  time: string;
  time_precision: TimePrecision;
  value?: (number | null) | undefined;
};
type SeriesKey = string;
type ArtifactId = string;
type ObservationStatus =
  | "normal"
  | "estimated"
  | "forecast"
  | "imputed"
  | "missing"
  | "provisional"
  | "revised"
  | "break";
type TimePrecision = "day" | "week" | "month" | "quarter" | "year";
type ObservationsMetadata = {
  attribution: string;
  dataflow: DataflowId;
  license: string;
  source_url: string;
};
type ObservationsResponse = {
  metadata: ObservationsMetadata;
  observations: Array<ObservationsRow>;
  pagination: PaginationMetadata;
};
type ObservationsRow = {
  attributes: {};
  dimensions: {};
  ingested_at: string;
  measure_id: string;
  revision_no: number;
  series_key: SeriesKey;
  source_artifact_id: ArtifactId;
  status: ObservationStatus;
  time: string;
  time_precision: TimePrecision;
  unit: string;
  value?: (number | null) | undefined;
};
type PaginationMetadata = Partial<{
  next_cursor: string | null;
}>;
type SearchResponse = {
  query: string;
  results: Array<SearchResult>;
};
type SearchResult = {
  dataflow_ids: Array<DataflowId>;
  description?: (string | null) | undefined;
  id: string;
  kind: SearchResultKind;
  name: string;
  score: number;
  source_id?: (null | SourceId) | undefined;
};
type SearchResultKind = "dataflow" | "measure";
type Series = {
  active: boolean;
  dataflow_id: DataflowId;
  dimensions: {};
  first_observed?: (string | null) | undefined;
  last_observed?: (string | null) | undefined;
  measure_id: MeasureId;
  series_key: SeriesKey;
  unit: string;
};
type SeriesLookupResponse = {
  latest_observation?: (null | Observation) | undefined;
  revision?: (null | SeriesRevisionMetadata) | undefined;
  series: Series;
};
type SeriesRevisionMetadata = {
  ingested_at: string;
  is_revision: boolean;
  revision_no: number;
  source_artifact_id: ArtifactId;
};

const DimensionId = z.string();
const Frequency = z.enum([
  "daily",
  "weekly",
  "monthly",
  "quarterly",
  "annual",
  "irregular",
]);
const DataflowId = z.string();
const License = z.union([
  z.literal("CC-BY-4.0"),
  z.literal("CC-BY-ND-4.0"),
  z.literal("CC-BY-SA-4.0"),
  z.literal("public-domain"),
  z.object({ other: z.string() }).passthrough(),
]);
const MeasureId = z.string();
const SourceId = z.string();
const Dataflow: z.ZodType<Dataflow> = z
  .object({
    attribution: z.string(),
    description: z.union([z.string(), z.null()]).optional(),
    dimensions: z.array(DimensionId),
    frequency: Frequency,
    id: DataflowId,
    license: License,
    measures: z.array(MeasureId),
    name: z.string(),
    source_id: SourceId,
    source_url: z.string(),
  })
  .passthrough();
const DataflowsResponse: z.ZodType<DataflowsResponse> = z
  .object({ dataflows: z.array(Dataflow) })
  .passthrough();
const CodelistId = z.string();
const Dimension: z.ZodType<Dimension> = z
  .object({
    codelist_id: CodelistId,
    description: z.union([z.string(), z.null()]).optional(),
    id: DimensionId,
    name: z.string(),
    position: z.number().int().gte(0),
  })
  .passthrough();
const DataflowDetailResponse: z.ZodType<DataflowDetailResponse> = z
  .object({ dataflow: Dataflow, dimensions: z.array(Dimension) })
  .passthrough();
const CodeId = z.string();
const Code: z.ZodType<Code> = z
  .object({
    codelist_id: CodelistId,
    description: z.union([z.string(), z.null()]).optional(),
    id: CodeId,
    name: z.string(),
    parent_id: z.union([z.null(), CodeId]).optional(),
  })
  .passthrough();
const Codelist: z.ZodType<Codelist> = z
  .object({
    codes: z.array(Code),
    description: z.union([z.string(), z.null()]).optional(),
    id: CodelistId,
    name: z.string(),
  })
  .passthrough();
const DataflowCodelistResponse: z.ZodType<DataflowCodelistResponse> = z
  .object({
    codelist: Codelist,
    dataflow_id: DataflowId,
    dimension_id: DimensionId,
  })
  .passthrough();
const Axis = z.enum(["throughput", "orientation"]);
const Direction = z.enum(["higher_is_better", "lower_is_better"]);
const Confidence = z.enum(["high", "medium", "low"]);
const CoverageStatus = z.enum([
  "resolved",
  "stale",
  "missing_expected",
  "coverage_gap",
  "manual_pending",
  "visible_unscored",
]);
const ScoreZone = z.enum(["red", "yellow", "green"]);
const Trend = z.enum(["up", "down", "flat", "unavailable"]);
const Normalization: z.ZodType<Normalization> = z
  .object({ best: z.number(), worst: z.number() })
  .passthrough();
const Provenance: z.ZodType<Provenance> = z
  .object({
    attribution: z.string(),
    license: z.string(),
    notes: z.union([z.string(), z.null()]).optional(),
    retrieved_at: z.union([z.string(), z.null()]).optional(),
    reviewed_at: z.union([z.string(), z.null()]).optional(),
    reviewed_by: z.union([z.string(), z.null()]).optional(),
    source_url: z.string(),
  })
  .passthrough();
const IndicatorConfig: z.ZodType<IndicatorConfig> = z
  .object({
    axis: Axis,
    cadence: z.string(),
    component: z.string(),
    confidence: Confidence,
    coverage_status: CoverageStatus,
    description: z.string(),
    dimension_selector: z.record(z.string()).optional(),
    direction: Direction,
    display_label: z.string(),
    indicator_id: z.string(),
    measure_id: z.string(),
    normalization: Normalization,
    provenance: Provenance,
    source_dataflow_id: z.string(),
    unit: z.string(),
    weight: z.number(),
  })
  .passthrough();
const ScorecardConfig: z.ZodType<ScorecardConfig> = z
  .object({
    attribution: z.string(),
    description: z.string(),
    formula: z.string(),
    id: z.string(),
    indicators: z.array(IndicatorConfig),
    label: z.string(),
    license: z.string(),
    version: z.string(),
  })
  .passthrough();
const ConfidenceBand: z.ZodType<ConfidenceBand> = z
  .object({ high: z.number(), low: z.number() })
  .passthrough();
const ComponentScore: z.ZodType<ComponentScore> = z
  .object({
    component: z.string(),
    coverage_pct: z.number(),
    score: z.number(),
    weight: z.number(),
  })
  .passthrough();
const SubIndexScore: z.ZodType<SubIndexScore> = z
  .object({
    axis: Axis,
    components: z.array(ComponentScore),
    confidence_band: ConfidenceBand,
    coverage_pct: z.number(),
    score: z.number(),
    weight: z.number(),
  })
  .passthrough();
const IndicatorContribution: z.ZodType<IndicatorContribution> = z
  .object({
    attribution: z.string(),
    axis: Axis,
    component: z.string(),
    confidence: Confidence,
    coverage_status: CoverageStatus,
    dimensions: z.record(z.string()),
    direction: Direction,
    indicator_id: z.string(),
    label: z.string(),
    latest_period: z.union([z.string(), z.null()]).optional(),
    license: z.string(),
    measure_id: z.string(),
    normalized_value: z.union([z.number(), z.null()]).optional(),
    notes: z.union([z.string(), z.null()]).optional(),
    raw_value: z.union([z.number(), z.null()]).optional(),
    series_key: z.union([z.string(), z.null()]).optional(),
    source_artifact_id: z.union([z.string(), z.null()]).optional(),
    source_dataflow_id: z.string(),
    source_url: z.string(),
    unit: z.string(),
    weight: z.number(),
  })
  .passthrough();
const ScorecardSnapshot: z.ZodType<ScorecardSnapshot> = z
  .object({
    as_of: z.string(),
    confidence: Confidence,
    confidence_band: ConfidenceBand,
    config_version: z.string(),
    contributions: z.array(IndicatorContribution),
    coverage_pct: z.number(),
    latest_period: z.union([z.string(), z.null()]).optional(),
    score: z.number(),
    scorecard_id: z.string(),
    sub_indexes: z.array(SubIndexScore),
    trend: Trend,
    zone: ScoreZone,
  })
  .passthrough();
const ScorecardSnapshotList = z.array(ScorecardSnapshot);
const HealthResponse = z.object({ status: z.string() }).passthrough();
const ObservationsMetadata: z.ZodType<ObservationsMetadata> = z
  .object({
    attribution: z.string(),
    dataflow: DataflowId,
    license: z.string(),
    source_url: z.string(),
  })
  .passthrough();
const SeriesKey = z.string();
const ArtifactId = z.string();
const ObservationStatus = z.enum([
  "normal",
  "estimated",
  "forecast",
  "imputed",
  "missing",
  "provisional",
  "revised",
  "break",
]);
const TimePrecision = z.enum(["day", "week", "month", "quarter", "year"]);
const ObservationsRow: z.ZodType<ObservationsRow> = z
  .object({
    attributes: z.record(z.string()),
    dimensions: z.record(z.string()),
    ingested_at: z.string().datetime({ offset: true }),
    measure_id: z.string(),
    revision_no: z.number().int().gte(0),
    series_key: SeriesKey.min(64).max(64),
    source_artifact_id: ArtifactId.min(64).max(64),
    status: ObservationStatus,
    time: z.string().datetime({ offset: true }),
    time_precision: TimePrecision,
    unit: z.string(),
    value: z.union([z.number(), z.null()]).optional(),
  })
  .passthrough();
const PaginationMetadata: z.ZodType<PaginationMetadata> = z
  .object({ next_cursor: z.union([z.string(), z.null()]) })
  .partial()
  .passthrough();
const ObservationsResponse: z.ZodType<ObservationsResponse> = z
  .object({
    metadata: ObservationsMetadata,
    observations: z.array(ObservationsRow),
    pagination: PaginationMetadata,
  })
  .passthrough();
const SearchResultKind = z.enum(["dataflow", "measure"]);
const SearchResult: z.ZodType<SearchResult> = z
  .object({
    dataflow_ids: z.array(DataflowId),
    description: z.union([z.string(), z.null()]).optional(),
    id: z.string(),
    kind: SearchResultKind,
    name: z.string(),
    score: z.number(),
    source_id: z.union([z.null(), SourceId]).optional(),
  })
  .passthrough();
const SearchResponse: z.ZodType<SearchResponse> = z
  .object({ query: z.string(), results: z.array(SearchResult) })
  .passthrough();
const Observation: z.ZodType<Observation> = z
  .object({
    attributes: z.record(z.string()),
    ingested_at: z.string().datetime({ offset: true }),
    revision_no: z.number().int().gte(0),
    series_key: SeriesKey.min(64).max(64),
    source_artifact_id: ArtifactId.min(64).max(64),
    status: ObservationStatus,
    time: z.string().datetime({ offset: true }),
    time_precision: TimePrecision,
    value: z.union([z.number(), z.null()]).optional(),
  })
  .passthrough();
const SeriesRevisionMetadata: z.ZodType<SeriesRevisionMetadata> = z
  .object({
    ingested_at: z.string().datetime({ offset: true }),
    is_revision: z.boolean(),
    revision_no: z.number().int().gte(0),
    source_artifact_id: ArtifactId.min(64).max(64),
  })
  .passthrough();
const Series: z.ZodType<Series> = z
  .object({
    active: z.boolean(),
    dataflow_id: DataflowId,
    dimensions: z.record(CodeId),
    first_observed: z.union([z.string(), z.null()]).optional(),
    last_observed: z.union([z.string(), z.null()]).optional(),
    measure_id: MeasureId,
    series_key: SeriesKey.min(64).max(64),
    unit: z.string(),
  })
  .passthrough();
const SeriesLookupResponse: z.ZodType<SeriesLookupResponse> = z
  .object({
    latest_observation: z.union([z.null(), Observation]).optional(),
    revision: z.union([z.null(), SeriesRevisionMetadata]).optional(),
    series: Series,
  })
  .passthrough();
const CreateSubscriptionRequest: z.ZodType<CreateSubscriptionRequest> = z
  .object({ dataflow_ids: z.array(DataflowId).optional(), url: z.string() })
  .passthrough();
const SubscriptionDetails: z.ZodType<SubscriptionDetails> = z
  .object({
    created_at: z.string().datetime({ offset: true }),
    dataflow_ids: z.array(DataflowId),
    id: z.string().uuid(),
    signing_secret: z.string(),
    status: z.string(),
    url: z.string(),
  })
  .passthrough();
const CreateSubscriptionResponse: z.ZodType<CreateSubscriptionResponse> = z
  .object({ subscription: SubscriptionDetails })
  .passthrough();
const DataflowsQuery: z.ZodType<DataflowsQuery> = z
  .object({
    frequency: z.union([z.null(), Frequency]),
    source: z.union([z.null(), SourceId]),
  })
  .partial()
  .passthrough();
const ProblemDetails = z
  .object({
    detail: z.union([z.string(), z.null()]).optional(),
    instance: z.union([z.string(), z.null()]).optional(),
    status: z.number().int().gte(0),
    title: z.string(),
    type: z.string(),
  })
  .passthrough();
const SearchQuery = z
  .object({ limit: z.union([z.number(), z.null()]).optional(), q: z.string() })
  .passthrough();

export const schemas = {
  DimensionId,
  Frequency,
  DataflowId,
  License,
  MeasureId,
  SourceId,
  Dataflow,
  DataflowsResponse,
  CodelistId,
  Dimension,
  DataflowDetailResponse,
  CodeId,
  Code,
  Codelist,
  DataflowCodelistResponse,
  Axis,
  Direction,
  Confidence,
  CoverageStatus,
  ScoreZone,
  Trend,
  Normalization,
  Provenance,
  IndicatorConfig,
  ScorecardConfig,
  ConfidenceBand,
  ComponentScore,
  SubIndexScore,
  IndicatorContribution,
  ScorecardSnapshot,
  ScorecardSnapshotList,
  HealthResponse,
  ObservationsMetadata,
  SeriesKey,
  ArtifactId,
  ObservationStatus,
  TimePrecision,
  ObservationsRow,
  PaginationMetadata,
  ObservationsResponse,
  SearchResultKind,
  SearchResult,
  SearchResponse,
  Observation,
  SeriesRevisionMetadata,
  Series,
  SeriesLookupResponse,
  CreateSubscriptionRequest,
  SubscriptionDetails,
  CreateSubscriptionResponse,
  DataflowsQuery,
  ProblemDetails,
  SearchQuery,
};
