name: Merge Queue

on:
  merge_group:
    types:
      - checks_requested

concurrency:
  group: merge-${{ github.sha }}
  cancel-in-progress: true

jobs:
  merge-queue:
    name: Merge Queue Checks
    uses: ./.github/workflows/pr.yml
    with:
      merge_queue: true
    secrets: inherit
